DEFAULT_SCREEN_WIDTH = 1800
DEFAULT_SCREEN_HEIGHT = 1000

DEFAULT_FONT = "Helvetica"
DEFAULT_HEADERS_SIZE = 20
DEFAULT_SUBHEADERS_SIZE = 15
DEFAULT_FONT_SIZE = 10
DEFAULT_PADDING = 10

LIGHT_BG_HEX = '#ABB6C2'
DARK_FG_HEX = '#20374C'

MAX_ROWS = 10
MAX_COLS = 15
DEFAULT_WORKER_THREADS = 15
MIN_PRISONER_COUNT = 2
DEFAULT_PRISONERS_COUNT = 100
MAX_PRISONER_COUNT = 150
MIN_SIMULATIONS_COUNT = 1000
MAX_SIMULATIONS_COUNT = 5000
SIMULATION_SPEED_SLOW = 1.5
SIMULATION_SPEED_FAST = 0.2
RANDOM_STRATEGY = 0
OPTIMIZED_STRATEGY = 1
NO_STRATEGY_SELECTED = -1
